motif_gates:
  bullish_reversal:
    min_entropy: 0.045
    ema_fast: 8
    ema_slow: 21
    min_volume_z: 0.3
  bearish_reversal:
    max_entropy: 0.12
    ema_fast: 8
    ema_slow: 21
    max_volume_z: -0.3
entropy:
  collapse_threshold: 0.25
  expansion_threshold: 0.75
  histogram_bins: 12
emotional_drift:
  volatility_window: 14
  volume_spike_threshold: 1.8
  sentiment_smoothing: 5
roi_resonance:
  profit_weight: 0.7
  risk_weight: 0.2
  conviction_weight: 0.1
capsule:
  output_path: data/capsules.jsonl
  ensure_directory: true
narrative:
  tone: mythic
  include_entropy_regime: true
exchange:
  name: binance
  sandbox_mode: true
  enable_paper: true
simulation:
  seed: 7
  bars: 180
  symbol: BTC/USDT
  timeframe: 1h
  expected_return: 0.001
  volatility: 0.01
risk:
  per_trade_risk_pct: 0.75
  daily_loss_cap_pct: 2.0
  weekly_loss_cap_pct: 5.0
  streak_downshift_losses: 3
  streak_multiplier: 0.6
  recover_wins: 2
  recover_step: 0.1
  max_multiplier: 1.0
sizing:
  base_qty: 1.0
  atr_lookback: 14
  atr_ref: 1.0
  conviction_boost: 1.5
  max_qty: 10.0
exits:
  r1_partial: 1.0
  r2_partial: 2.0
  trail_atr_mult: 1.5
  entropy_fail_safe: 0.65
  flip_on_regime_change: true
  partial_pct: 0.25
