name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: flake8 src tests scripts
      - name: Run tests
        run: pytest
      - name: Execute notebook
        run: jupyter nbconvert --to notebook --execute notebooks/simulation.ipynb --output notebooks/simulation.ci.ipynb
      - name: Generate visualization artifact
        run: python scripts/generate_visualization.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: oracle-rituals
          path: |
            artifacts/*.png
            artifacts/*.csv
            notebooks/simulation.ci.ipynb
