name: IO Schema Validation

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install -r requirements.txt
      - name: Validate samples via loader + CLI
        run: |
          make io-validate
          python scripts/io_cli.py summarize --kind returns --path samples/strategy_returns.ndjson
      - name: Unit tests
        run: |
          make test
