name: IO Schema Validation

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install jsonschema
      - name: Validate samples
        run: |
          python scripts/validate_io.py --schema common/schema/brain.signal.json --file samples/brain_signals.ndjson
          python scripts/validate_io.py --schema common/schema/oracle.trade_event.json --file samples/trade_events.ndjson
          python scripts/validate_io.py --schema common/schema/oracle.strategy_return.json --file samples/strategy_returns.ndjson
          python scripts/validate_io.py --schema common/schema/portfolio.allocation.json --file samples/portfolio_allocation.json
